"""Personal mailbox detection processor (T2).

Runs phishing + spam detection on pending personal_mails rows.
Called from personal_mailbox_poller after metadata ingest.

Privacy: body is fetched transiently from IMAP, used for scanning,
then discarded — never written to any DB column.

Extension points:
  T4: folder_action set here ('move_quarantine'/'move_spam'/'none');
      personal_imap.move_to_folder() called in T4.
"""
import json
import logging

from app.services import personal_imap, phishing_detector, spam_detector
from app.services.sender_lists import entry_tip as _entry_tip

logger = logging.getLogger("mailguard.personal_processor")

_SETTINGS_KEY = "personal_phishing_manual_learning"
_ACCOUNT_SENDERLIST_KEY = "personal_mailbox_senderlist_{}"
SPAM_THRESHOLD = 30


def _load_personal_lists(cur, account_id: int | None = None) -> tuple[set, set]:
    """Returns (personal_blacklist, personal_whitelist) sets from settings KV.

    If account_id is given, loads per-account list (key personal_mailbox_senderlist_{id}).
    Falls back to global per-user list (personal_phishing_manual_learning) if per-account
    list is empty or missing.
    """
    personal_blacklist: set = set()
    personal_whitelist: set = set()

    def _parse_store(store: dict) -> tuple[set, set]:
        bl: set = set()
        wl: set = set()
        for k, v in (store.get("blacklist") or {}).items():
            if not k or (isinstance(v, dict) and v.get("muted")):
                continue
            tip = _entry_tip(v if isinstance(v, dict) else {})
            if tip == "carantina":
                bl.add(k.lower())
        for k, v in (store.get("whitelist") or {}).items():
            if k and not (isinstance(v, dict) and v.get("muted")):
                wl.add(k.lower())
        return bl, wl

    try:
        # Per-account list takes priority when account_id provided
        if account_id is not None:
            acct_key = _ACCOUNT_SENDERLIST_KEY.format(account_id)
            cur.execute("SELECT value FROM settings WHERE key=%s", (acct_key,))
            row = cur.fetchone()
            store = row["value"] if row and row["value"] else {}
            if store.get("blacklist") or store.get("whitelist"):
                return _parse_store(store)

        # Global per-user fallback
        cur.execute("SELECT value FROM settings WHERE key=%s", (_SETTINGS_KEY,))
        row = cur.fetchone()
        store = row["value"] if row and row["value"] else {}
        personal_blacklist, personal_whitelist = _parse_store(store)
    except Exception:
        logger.exception("personal lists load failed")
    return personal_blacklist, personal_whitelist


def _detect(mail: dict, account: dict, password: str,
            personal_blacklist: set, personal_whitelist: set) -> tuple[str, str, list]:
    """Fetch body transiently, run detection, discard body.

    Returns (verdict, folder_action, combined_reasons).
    verdict: 'clean' | 'spam' | 'quarantined'
    folder_action: 'none' | 'move_spam' | 'move_quarantine'
    """
    uid = mail["imap_uid"]
    from_address = mail.get("from_address") or ""
    subject = mail.get("subject") or ""

    # Fetch body transiently — never written to DB
    body_text, body_html, extra_headers = personal_imap.fetch_message_body(account, password, uid)

    email_dict = {
        "from_address": from_address,
        "subject": subject,
        "body_text": body_text,
        "body_html": body_html,
        "from_name": "",
    }

    # Auto-generated / no-reply detection (personal mailboxes only — T2 gate)
    try:
        autogen_score, autogen_reasons = spam_detector.detect_autogenerated(
            email_dict, extra_headers=extra_headers
        )
    except Exception:
        logger.exception(f"detect_autogenerated failed account={account.get('id')} uid={uid}")
        autogen_score, autogen_reasons = 0.0, []

    if autogen_score >= SPAM_THRESHOLD:
        # body_text + body_html go out of scope here — never persisted
        return "spam", "move_spam", autogen_reasons

    # Phishing/quarantine detection (reutilizează motorul CTS)
    try:
        score, ph_status, ph_reasons = phishing_detector.detect_phishing(
            email_dict,
            attachments=[],
            suppress_codes=set(),          # fără suppression_rules personal în V1
            blacklist=personal_blacklist,
            whitelist=personal_whitelist,
        )
    except Exception:
        logger.exception(f"detect_phishing failed account={account.get('id')} uid={uid}")
        ph_status, ph_reasons = "clean", []

    # Spam detection (heuristici pure, fără reputație în V1)
    try:
        spam_score, spam_reasons = spam_detector.detect_spam(email_dict)
    except Exception:
        logger.exception(f"detect_spam failed account={account.get('id')} uid={uid}")
        spam_score, spam_reasons = 0.0, []

    # Verdict final: carantina > spam > clean
    if ph_status in ("quarantined", "quarantined_strict"):
        verdict = "quarantined"
        folder_action = "move_quarantine"
        combined = ph_reasons
    elif spam_score >= SPAM_THRESHOLD:
        verdict = "spam"
        folder_action = "move_spam"
        combined = spam_reasons
    else:
        verdict = "clean"
        folder_action = "none"
        combined = ph_reasons + spam_reasons

    # body_text + body_html go out of scope here — never persisted
    return verdict, folder_action, combined


def process_account_pending(account: dict, password: str, cur, conn) -> int:
    """Run detection on all pending mails for one account. Returns count processed."""
    account_id = account["id"]

    cur.execute("""
        SELECT id, imap_uid, from_address, subject
        FROM personal_mails
        WHERE account_id = %s AND verdict = 'pending'
        ORDER BY imap_uid
    """, (account_id,))
    pending = [dict(r) for r in cur.fetchall()]

    if not pending:
        return 0

    personal_blacklist, personal_whitelist = _load_personal_lists(cur, account_id)
    processed = 0

    for mail in pending:
        try:
            verdict, folder_action, reasons = _detect(
                mail, account, password, personal_blacklist, personal_whitelist
            )
            cur.execute("""
                UPDATE personal_mails
                SET verdict = %s,
                    verdict_reason = %s::jsonb,
                    folder_action = %s
                WHERE id = %s
            """, (verdict, json.dumps(reasons), folder_action, mail["id"]))
            processed += 1

            if verdict != "clean":
                logger.info(
                    f"account {account_id} uid={mail['imap_uid']}: "
                    f"verdict={verdict} folder_action={folder_action}"
                )
        except Exception:
            logger.exception(
                f"process_account_pending failed account={account_id} mail_id={mail['id']}"
            )

    conn.commit()
    return processed
