-- T2 personal mailbox: auto-generated / no-reply spam detection rule
-- Catalog entry (informational seed — rulele sunt definite în cod, în settings.py SPAM_RULES_CATALOG).
-- Dacă în viitor catalogul se mută în DB, acest seed devine load-bearing.
-- Idempotent: ON CONFLICT DO NOTHING.

-- Nu există tabel spam_rules în schema curentă — nicio modificare DDL necesară.
-- Regula e activă automat via detect_autogenerated() în personal_mail_processor.py.
-- Această migrație documentează release-ul și poate fi extinsă când catalogul se mută în DB.

SELECT 'personal_spam_autogenerated: rule active in code (spam_detector.detect_autogenerated), no DDL required' AS migration_status;
